# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  bname = "kod";
  name = "kod-unstable-${version}";
  version = "2017-10-30";
  rev = "111dbb29f57dd2c8963754c38230582ce7ce5b31";

  goPackagePath = "github.com/linde12/kod";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/linde12/kod.git";
    sha256 = "00wb53znq21gjglfxgpf2qj3rprfvwi9pfx7qbsc5w7hhciyn3bc";
  };

  goDeps = ./deps.nix;

  meta = with stdenv.lib; {
    description = "terminal text editor written in Go, using xi-editor as backend";
    homepage = https://github.com/linde12/kod;
    license = licenses.mit;
    maintainers = with maintainers; [ ayyjayess ];
    platforms = with platforms; all;
  };
}
