# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/gdamore/encoding";
    fetch = {
      type = "git";
      url = "https://github.com/gdamore/encoding";
      rev = "b23993cbb6353f0e6aa98d0ee318a34728f628b9";
      sha256 = "0d7irqpx2fa9vkxgkhf04yiwazsm10fxh0yk86x5crflhph5fv8a";
    };
  }
  {
    goPackagePath = "github.com/gdamore/tcell";
    fetch = {
      type = "git";
      url = "https://github.com/gdamore/tcell";
      rev = "40c3b117ed496996c8482be266e60583ca988b09";
      sha256 = "04mzsncx4hh13aq0sjcjpa4v12d9sr5r7lprsfnkfybbyhc3a9zw";
    };
  }
  {
    goPackagePath = "github.com/lucasb-eyer/go-colorful";
    fetch = {
      type = "git";
      url = "https://github.com/lucasb-eyer/go-colorful";
      rev = "231272389856c976b7500c4fffcc52ddf06ff4eb";
      sha256 = "161n224v46mln3swzv0009ffj9fxg2n814l9vqs3zh9dq1dmj0jn";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-runewidth";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-runewidth";
      rev = "97311d9f7767e3d6f422ea06661bc2c7a19e8a5d";
      sha256 = "0dxlrzn570xl7gb11hjy1v4p3gw3r41yvqhrffgw95ha3q9p50cg";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "e19ae1496984b1c655b8044a65c0300a3c878dd3";
      sha256 = "1cvnnx8nwx5c7gr6ajs7sldhbqh52n7h6fsa3i21l2lhx6xrsh4w";
    };
  }
]
